#!/usr/bin/env python3
"""Generate a bilingual localization Word document from translated JSONL.

Lightweight fallback when the anthropic-skills:docx skill is unavailable.

Usage:
    python scripts/to_docx.py translated.jsonl -o output.docx [--title "Series Title"]

Input JSONL format (one object per line):
    {"id": "EP01_001", "type": "dialogue", "speaker": "林清越", "raw": "...", "en": "...", "note": "..."}

Requires: python-docx (pip install python-docx)
"""

import argparse
import json
import os
import re
import sys

try:
    from docx import Document
    from docx.shared import Inches, Pt, Cm, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
except ImportError:
    print(
        "Error: python-docx is required. Install with: pip install python-docx",
        file=sys.stderr,
    )
    sys.exit(1)


def _episode_from_id(record_id: str) -> str:
    """Extract episode label from record ID like EP01_001."""
    m = re.match(r"(EP\d+)", record_id)
    return m.group(1) if m else "EP00"


def build_document(records: list[dict], title: str) -> Document:
    """Build a Word document from translated JSONL records."""

    doc = Document()

    # Title
    heading = doc.add_heading(title, level=0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Group records by episode
    episodes: dict[str, list[dict]] = {}
    for rec in records:
        ep = _episode_from_id(rec.get("id", "EP00_000"))
        episodes.setdefault(ep, []).append(rec)

    for ep_key in sorted(episodes.keys()):
        ep_records = episodes[ep_key]
        ep_num = ep_key.replace("EP", "").lstrip("0") or "0"

        # Episode heading
        doc.add_heading(f"Episode {ep_num}", level=1)

        # Create table
        table = doc.add_table(rows=1, cols=5)
        table.style = "Table Grid"
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        # Header row
        headers = ["#", "Type", "Chinese", "English", "Notes"]
        for i, h in enumerate(headers):
            cell = table.rows[0].cells[i]
            cell.text = h
            for para in cell.paragraphs:
                for run in para.runs:
                    run.bold = True
                    run.font.size = Pt(9)

        # Data rows
        for rec in ep_records:
            row = table.add_row()
            row.cells[0].text = rec.get("id", "")
            row.cells[1].text = rec.get("type", "")

            # Speaker prefix for dialogue
            raw = rec.get("raw", "")
            speaker = rec.get("speaker")
            if speaker and rec.get("type") == "dialogue":
                raw = f"{speaker}：{raw}"
            row.cells[2].text = raw

            row.cells[3].text = rec.get("en", rec.get("english", ""))
            row.cells[4].text = rec.get("note", rec.get("risk_note", ""))

            # Font size
            for cell in row.cells:
                for para in cell.paragraphs:
                    for run in para.runs:
                        run.font.size = Pt(8)

        # Set column widths (approximate)
        for row in table.rows:
            row.cells[0].width = Cm(1.8)
            row.cells[1].width = Cm(1.8)
            row.cells[2].width = Cm(6.0)
            row.cells[3].width = Cm(6.0)
            row.cells[4].width = Cm(3.0)

        doc.add_paragraph()  # spacing between episodes

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph("Generated by subtitle-export-localization skill")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    return doc


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate bilingual Word document from translated JSONL."
    )
    parser.add_argument("input", help="Path to translated JSONL file")
    parser.add_argument(
        "-o", "--output",
        default=None,
        help="Output .docx path (default: <input_stem>.docx)",
    )
    parser.add_argument(
        "--title",
        default="Subtitle Localization — Bilingual Script",
        help="Document title",
    )
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"Error: file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    stem = os.path.splitext(args.input)[0]
    output_path = args.output or f"{stem}.docx"

    # Read JSONL
    records: list[dict] = []
    with open(args.input, "r", encoding="utf-8") as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as e:
                print(
                    f"Warning: skipping malformed JSON at line {line_num}: {e}",
                    file=sys.stderr,
                )

    if not records:
        print("Error: no records found in input file.", file=sys.stderr)
        sys.exit(1)

    doc = build_document(records, args.title)
    doc.save(output_path)

    print(f"Generated {output_path} ({len(records)} lines, {os.path.getsize(output_path)} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
